GRANT ALL PRIVILEGES ON DATABASE sportiza TO dperaltav; 
GRANT ALL PRIVILEGES ON DATABASE sportiza TO anguyen120; 


GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO dperaltav;
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO anguyen120;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dperaltav;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dperaltav;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anguyen120;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anguyen120;